# Generated by Django 4.2.26 on 2025-11-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='uploaded', max_length=50)),
                ('extracted_text', models.JSONField(blank=True, null=True)),
                ('key_values', models.JSONField(blank=True, null=True)),
                ('tables', models.JSONField(blank=True, null=True)),
                ('errors', models.TextField(blank=True)),
            ],
        ),
    ]
