# Generated by Django 4.2.26 on 2025-11-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs_app', '0002_document_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_text_input',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to='docs/'),
        ),
    ]
